#!/usr/bin/env python
import RPi.GPIO as GPIO
import time
from subprocess import call

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BOARD)
pin_to_circuit = 7
lux = 10000

def rc_time(pin_to_circuit):
    count = 0
    GPIO.setup(pin_to_circuit, GPIO.OUT)
    GPIO.output(pin_to_circuit, GPIO.LOW)
    time.sleep(0.1)
    GPIO.setup(pin_to_circuit, GPIO.IN)
  
    while GPIO.input(pin_to_circuit) == GPIO.LOW:
        count += 1

    return count
	
try:	
    screen_on = False  # Variable para rastrear el estado de la pantalla encendida
    while True:
        i = rc_time(pin_to_circuit)
        if i < lux:
            if not screen_on:
                print("Screen on", i)
                call(["/usr/bin/vcgencmd", "display_power", "1"])
                screen_on = True
        else:
            if screen_on:
                print("Screen off in 5 seconds", i)
                time.sleep(5)
                i = rc_time(pin_to_circuit)  # Verificar nuevamente el valor después del desfase
                if i >= lux:
                    print("Screen off", i)
                    call(["/usr/bin/vcgencmd", "display_power", "0"])
                    screen_on = False
        
        time.sleep(1)
except KeyboardInterrupt:
    print("Program interrupted by the user")
finally:
    GPIO.cleanup()
